version: "3.2"
services:
  react-app:
    container_name: germaniii-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    volumes:
      - .:/app
      - /app/node_modules
